### ISSUE TITLE
where the dots

### ISSUE THREAD

**Issue by TassiloBalbo** [rxyhn/wkwkland#1]
OP deliver pls

**Comment by l3gacyb3ta** [comment]
yeah lmao

**Comment by TheHolyTachanka** [comment]
Imagine making a beautiful rice, posting on reddit just to not give th dots, smh

**Comment by sioodmy** [comment]
cry about it

**Comment by JxJxxJxJ** [comment]
Lol

**Comment by l3gacyb3ta** [comment]
lmao

**Comment by TheHolyTachanka** [comment]
This guy is fun at parties

**Comment by sioodmy** [comment]
> This guy is fun at parties

hope you get drafted to ukraine and killed like most of you lmao

**Comment by l3gacyb3ta** [comment]
o damn lol. we just liked the cool tech stuff lol

**Comment by l3gacyb3ta** [comment]
oh wait lol yeah no @TheHolyTachanka why

**Comment by TheHolyTachanka** [comment]
> > This guy is fun at parties
> 
> hope you get drafted to ukraine and killed like most of you lmao

Thats your only argument?

**Comment by sioodmy** [comment]
yeah
